### ISSUE TITLE
导航栏中 Donate v.s. Donation

### ISSUE THREAD

**Issue by xuchunyang** [emacs-china/donate#3]
https://emacs-china.org/ 上用的是 Donate，http://donate.emacs-china.org/ 上用的是 Donation，应该统一下。我偏向于 Donate，短、含义也足够清楚。

**Comment by kuangdash** [comment]
这个是要改，年末要清理下 emacs-china 上的东西了，不然会越发混乱

我看了一下 donate 的情况，怎么突然支出了 1963.8？按理说三年的话，是不是要退回两年的 1024？求解释 @zilongshanren 

钱应该放在更有用的地方，而不是去侍奉 Alibaba

我觉得 emacs-china 需要人事更动了，不然大家的参与积极性都会降低，求各方意见

**Comment by zilongshanren** [comment]
@kuangdash 

这三年的 vps 购买是为了搭建论坛，因为没办法在我以前的 vps 上面同时跑 elpa 镜像和论坛。具体原因，可以在 https://emacs-china.org/t/discourse/1708/7 找到。

如果你可以在这台新的 vps 上面搭建 elpa 和论坛，我可以把 1024 退回来。另外，这 1024 本来就是我捐赠的，即使论坛到期，钱还是优先我出的。如果你认为我管理有问题，或者滥用钱，这事大可你来干，我没有意见。

@emacs-china/elpa-people

**Comment by ghost** [comment]
@kuangdash 我也是西安的呀，老乡呀老乡，泪汪汪

> 这个是要改，年末要清理下 emacs-china 上的东西了，不然会越发混乱

清理什么东西？

> 钱应该放在更有用的地方，而不是去侍奉 Alibaba 

现在除了转移服务器外还有什么呢？比如呢？

> 我觉得 emacs-china 需要人事更动了，不然大家的参与积极性都会降低，求各方意见

现在就主要子龙山人一个人在管理，你要变动什么人士？（“还要啥自行车！”）

@xuchunyang 我现在把两个都换成 Donate （改好了）

@kuangdash 如果还想关于这个问题进行讨论请去论坛开帖子，那里人比这里多。这个 Issue 我就关了，已经改完字了。

**Comment by xuchunyang** [comment]
@li-xinyang 但是后来 @zilongshanren 在 https://github.com/emacs-china/donate/commit/47c6999bb0a0a6a3ca860fc04b6241d513234b13 里改回去了，可能是需要改模板，后生成 index.html

**Comment by ghost** [comment]
对哦哦， 我忘了。。。我是写在模版里面了。谢谢提醒 💋  我现在去该下子

**Comment by zilongshanren** [comment]
@li-xinyang  刚好我也在改。。。 我又运行生成了新的 index.html，现在好了 @xuchunyang

**Comment by kuangdash** [comment]
@li-xinyang 我不是西安本地人啦，目前在西安电子科技大学读博，目前还是往返南昌（老家）和西安的状态

>清理什么东西？

about.emacs-china.org 打算怎么整合？emacs-china.github.io 怎么整合？我指的是目前 github repos 好像有点多，有前手有后手，我这里只是提议

> 现在就主要子龙山人一个人在管理，你要变动什么人士？（“还要啥自行车！”）

emacs-china.org 论坛要找人接替管理应该还是找的到的，你可以看 hick 先生的微信公众号，所谓人事更动是指如果老人没有继续维护的热情，那么怎么交接给有热情的新人？有学校社团经验的应该都知道，当然你要把我赶鸭子上架的话，我觉得凭我的个人智商应该没问题><

> 如果你可以在这台新的 vps 上面搭建 elpa 和论坛，我可以把 1024 退回来。另外，这 1024 本来就是我捐赠的，即使论坛到期，钱还是优先我出的。如果你认为我管理有问题，或者滥用钱，这事大可你来干，我没有意见。

前面是看到子龙兄你投入了这么多，所以我们这些人才乐意投入进行分担，你这样撤资不大好，而且在账面上也没有说清楚，后续谁再愿意 donate？

搭建论坛这件事，我挺吃惊，为啥要建这样的论坛？有 VPS 干啥不好呢？而且当时的技术趋势已经是 node 而不是 ruby 了，虽然 discourse 挺不错的，但是免费的论坛已经有很多了，至少专业点说，英文有 stackoverflow，中文有 segmentfault。

Elpa 这件事，是我觉得最应该放在 emacs-china 上由大家承担 VPS 费用的了，事实上也是对各方都好，这件事上先谢 @xuchunyang。当然国内最先搞的是 @aborn ，然后 @CodeFalling 也有能力独立设置个人的，但是何必呢？这玩意不能一起弄吗？

最后，emacs-china 上能做的事情很多，这里只是舞台。以上个人见解，喜欢就点赞，不喜欢就拉黑

**Comment by zilongshanren** [comment]
@kuangdash 
我觉得你可能还没搞清楚状态，about.emacs-china.org 可以删除，至于 emacs-china.github.io 这个可以论坛去投票。我知道你对 emacs-china.github.io 付出了很多，但是也希望你能接受社区的意见。当初搭建论坛而不是使用一个 org 的站点就是社区投票决定的。以后想怎么整合，可以继续发起投票，但是我相信，结果不会变。

至于花钱购买 VPS，这个 @xuchunyang  也是知情的，之前论坛搭在我个人的 vps 上面。这次购买的 vps 是专门用来搭建论坛的，上面除了论坛没有任何其他服务。

而我以前的 vps 目前托管了 elpa 的镜像，所以这两台 vps 都是在为社区服务的。

关于花钱如何花，我觉得这里面根本没啥好讨论的。首先，我不是阿里的员工，我没有必要用你们捐的这点钱来做一些对我个人有益的事，而且我也看不上。至于于滥用钱，我觉得你有点小题大作了。

可能你捐了钱，我作为用钱的人，没有征求大家的意见是有点不妥。但是，我想说的是，我做的一切都是从社区的角度出发，而完全没有自己的私利。

过多的我也不想讨论什么，如果你觉得不满意，你捐的部分我可以退回给你。如果还有谁不满意，我都可以退回。这点小钱，我还是出的起的。

**Comment by zilongshanren** [comment]
@kuangdash  
关于我捐的 1024 ，这个从中除名吧，包括之前的 linode, 因为这两台服务器确实不是”纯“的，因为托管了我个人的服务。

**Comment by xcodebuild** [comment]
@kuangdash

用 niginx 反代论坛和 elpa 值得做一下（如果可行的话），毕竟可以节省机器，@zilongshanren 试了一下似乎坑比较多，谁有兴趣也可以试试看。

提议人事变动可以单独发帖，说明自己希望管理的部分想法或者推荐的人选。如果如你所说你认为论坛应该直接关了那让你管论坛显然是不合理的😂。

对经费的疑问可以单独发贴，上面也解释了。

对论坛价值的质疑可以单独发帖。我个人认为论坛作为一个内容沉淀社区是有意义的，虽然最近自己时间比较混乱没怎么逛过。

最后 elpa mirror 其实和 @aborn 学长的有一定区别，我们只是直接从 melpa 等源拉最新的 archive。而 @aborn 做的是自行构建，可以自己加 melpa 不存在的包，也不受 melpa的影响。现行方案和我的方案的区别其实只是托管的方式不同，虽然方式我更赞同免费方案，但其实 elpa-china 落成后我就没有维护直接用这个了🙄毕竟免费的会有一些限制。

总之，我认为你提到的各种问题可以单独发 issue 或者帖子，更方便讨论。直接在一个技术问题的 issue 下面指责各种各样的问题显得有点单纯发泄不满的感觉，有建设性的讨论更有利于问题的解决。

**Comment by zilongshanren** [comment]
@kuangdash  @CodeFalling 

谁有能力在社区目前的 VPS 上面搭一个 elpa + 论坛的，可以把 ssh key 发给我，我给他加上去。

PS：目前我已把我的捐赠金额除名。elpa 镜像服务器继续服务，期待有能者能够在一台 VPS 上面实现论坛跟 elpa 镜像。至于vps 过期之后的续费，我还是那句”没人捐赠，我负责”。

**Comment by kuangdash** [comment]
> about.emacs-china.org 打算怎么整合？emacs-china.github.io 怎么整合？我指的是目前 github repos 好像有点多，有前手有后手，我这里只是提议

整合的事交给我试试，我的 id_rsa.pub:
[id_rsa.pub.zip](https://github.com/emacs-china/donate/files/629634/id_rsa.pub.zip)

然后是 EGO 的车，方向和设计都没错，不过剩下的算是工作了，缺乏乐趣= =

我没有说谁滥用钱，但是收了群众的钱肯定要有恰当的交代，之前那样不好。donate 的问题在 donate 的 issue 下解决啊。而且需要钱的话，为啥不试试 TyuuniBox？（卖个瓜）

至于我在发泄个人的不满这件事，你们想多了。（其实我觉得自己在指点江山，嘴炮命……）

我觉得群众投票也是要讲负责制的，不能什么票都算。不然广大宅男都呼喊要有大 JJ 的女孩子，然后？

**Comment by zilongshanren** [comment]
@CodeFalling 
nginx 反向代理试过 3 种方案，都无法访问，而阿里云下载速度慢得要死，操作一次 1个小时就没了。我觉得我的时间更值钱。而且社区用一台专门的 VPS，这个本来就更好。（关于 VPS 的管理者的归属，我觉得大家相信我就让我来管，目前我和 @xuchunyang  同学都有权限。服务器这种东西，如果一群人有权限，可能还更麻烦。而且我也不想用这台 VPS 干的别的什么，出了问题，累人。）

我觉得现在社区的东西都在一台 VPS 上面也挺好，elpa 暂时放在我个人的服务器上面，期待后面有人来搞定一台 VPS 同时跑多个站点。

我想说的就这么多了。 我希望 emacs 社区健康良性发展，我也不希望社区搞什么个人崇拜。我本人也只是一名 emacs 爱好者，我也不希望被人认为我用公家的钱赚名气什么的。

**Comment by zilongshanren** [comment]
@kuangdash 

你现在可以访问了，尽情折腾吧，骚年。

**Comment by zilongshanren** [comment]
@kuangdash 

  号称中国最好的 emacs 社区，大晚上讨论这种问题真的让人心寒，我还是把它关了吧？？？

**Comment by kuangdash** [comment]
@zilongshanren emacs-china.github.io 在手机上的显示有点问题了，http 打不开，得用 https（但是打开后的主题就没了），要用 EGO 重新发布了。 about.emacs-china.org 这个 repos 子龙兄处理吧。

@li-xinyang erb 模板的套法要用 ruby 和 gems 啊…我直接改网页文件行不行？

这里讨论的问题很正常，倒不如说没有讨论才不正常。

**Comment by ghost** [comment]
@kuangdash 你可以直接改吧 .erb 去掉就可以了 然后加自己要的东西 就可以吧（我猜你是想做一个一样样式的页面）
